// Run with Node and an installed Playwright package (test-only dependency).
// Uses fresh browser contexts; never reads or resets the user's browser storage.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { chromium } = require('playwright');
const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'output/playwright/workbench-redesign');
const URL = process.env.FINWISE_DEMO_URL || 'http://127.0.0.1:8766/static/operator-workbench-demo.html';
const report = [];
async function run() {
  fs.mkdirSync(OUT, { recursive: true });
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  const errors = [], requests = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => requests.push({ url: r.url(), type: r.resourceType() }));
  const click = action => page.locator('[data-action="' + action + '"]').first().click();
  const text = () => page.locator('main').innerText();
  const select = async id => {
    if (await page.locator('#mobileMenu').isVisible()) await click('open-menu');
    await page.locator('.company-main[data-id="' + id + '"]').click();
  };
  const percent = async expected => assert.equal(await page.locator('#overallPercent').textContent(), String(expected));
  const check = async (name, fn) => { await fn(); report.push({ name, passed: true }); console.log('PASS', name); };
  try {
    await page.goto(URL);
    await check('desktop first fold: scope, stages and a single actionable button', async () => {
      await percent(40);
      assert.equal(await page.locator('main .primary').count(), 1);
      assert.equal(await page.locator('#confirmationNote').isVisible(), true);
      assert.equal(await page.locator('.detail-tabs, [data-action="detail"]').count(), 0);
      assert.equal(await page.locator('#stageWorkspace').count(), 1);
      assert.equal(await page.locator('.stage.active').count(), 1);
      const b = await page.locator('main .primary').boundingBox();
      assert.ok(b.y >= 0 && b.y + b.height <= 900, JSON.stringify(b));
      const overlapping = await page.locator('.company-row').evaluateAll(rows => rows.some(row => {
        const a = row.querySelector('.company-license').getBoundingClientRect();
        const b = row.querySelector('.company-tools').getBoundingClientRect();
        return a.right > b.left || a.height < 16;
      }));
      assert.equal(overlapping, false);
      await page.screenshot({ path: path.join(OUT, 'desktop-1440.png') });
    });
    await check('anomaly does not interrupt the current note or switch enterprise', async () => {
      await page.locator('#confirmationNote').fill('客户正在补充合同，保留本条备注。');
      await page.locator('.sidebar-foot summary').click();
      await click('simulate-alert');
      assert.match(await page.locator('h1').innerText(), /聚贤达/);
      assert.equal(await page.locator('#confirmationNote').inputValue(), '客户正在补充合同，保留本条备注。');
      assert.equal(await page.locator('[data-company-row="luhai"].new').count(), 1);
      await page.locator('#alertBanner [data-action="dismiss-alert"]').click();
      assert.equal(await page.locator('.alert-banner').count(), 0);
    });
    await check('confirmation records, next-item focus and persistent evidence gates', async () => {
      await click('confirm');
      assert.match(await page.locator('#currentTaskTitle').innerText(), /付款/);
      await percent(40);
      assert.equal(await page.locator('#confirmationNote').inputValue(), '');
      await page.locator('#confirmationNote').fill('待客户补充付款计划');
      await click('confirm');
      assert.match(await text(), /核实已记录，等待补齐证据/);
      await percent(40);
      assert.equal(await page.locator('[data-action="confirm"]').count(), 0);
      await click('supplement');
      assert.match(await page.locator('dialog').innerText(), /采购合同/);
      await click('close-dialog');
      await page.reload();
      await percent(40);
      await page.locator('.queue-row summary').first().click();
      assert.match(await text(), /客户正在补充合同/);
    });
    await check('search and tag add/delete restore exactly across refresh', async () => {
      await page.locator('#companySearch').fill('XQY');
      assert.equal(await page.locator('.company-row').count(), 1);
      await page.locator('#companySearch').fill('');
      await page.locator('[data-action="tags"][data-id="juxianda"]').click();
      await page.locator('#newTag').fill('验收标签');
      await click('add-tag');
      await page.locator('[data-action="delete-tag"][data-tag="重点客户"]').click();
      await click('close-dialog');
      await page.reload();
      await page.locator('#companySearch').fill('验收标签');
      assert.equal(await page.locator('.company-row').count(), 1);
      await page.locator('[data-action="tags"][data-id="juxianda"]').click();
      assert.equal(await page.locator('dialog [data-tag="重点客户"]').count(), 0);
      await page.locator('[data-action="delete-tag"][data-tag="验收标签"]').click();
      await click('close-dialog');
      await page.reload();
      await page.locator('#companySearch').fill('验收标签');
      assert.equal(await page.locator('.company-row').count(), 0);
      await page.locator('#companySearch').fill('');
    });
    await check('switching enterprise does not leak notes, evidence or history', async () => {
      await select('huanyu');
      assert.equal(await page.locator('#confirmationNote').inputValue(), '');
      assert.doesNotMatch(await text(), /聚贤达|8,838|客户正在补充合同/);
      await page.locator('#confirmationNote').fill('环宇独立备注');
      await click('defer'); await click('defer'); await click('defer');
      assert.match(await text(), /还有 3 项暂缓事项/);
      await percent(40);
      await click('resume');
      assert.equal(await page.locator('#confirmationNote').inputValue(), '环宇独立备注');
      await page.locator('[data-action="tab"][data-tab="history"]').click();
      await click('history-period');
      await click('history-archive');
      await click('archive-voucher');
      assert.match(await page.locator('dialog').innerText(), /环宇新材料/);
      assert.doesNotMatch(await page.locator('dialog').innerText(), /聚贤达/);
      await click('close-dialog');
      await page.locator('[data-action="tab"][data-tab="current"]').click();
      assert.equal(await page.locator('#confirmationNote').inputValue(), '环宇独立备注');
    });
    await check('stage browsing is read-only and returns to the current task', async () => {
      assert.equal(await page.locator('[data-action="stage"][data-stage="4"]').isDisabled(), true);
      assert.equal(await page.locator('[data-action="stage"][data-stage="3"]').isDisabled(), true);
      await page.locator('[data-action="stage"][data-stage="0"]').click();
      assert.equal(await page.locator('#stageWorkspace').getAttribute('data-stage'), '0');
      assert.match(await page.locator('#stageWorkspace').innerText(), /本批已接收 18 份/);
      assert.equal(await page.locator('.stage.active').count(), 1);
      assert.equal(await page.locator('.stage.active').getAttribute('data-stage'), '0');
      assert.equal(await page.locator('.stage[aria-current="step"]').getAttribute('data-stage'), '2');
      assert.equal(await page.locator('main .primary').count(), 0);
      await percent(40);
      await page.screenshot({ path: path.join(OUT, 'single-stage-files-1440.png') });
      await page.locator('[data-action="stage"][data-stage="1"]').click();
      assert.match(await page.locator('#stageWorkspace').innerText(), /已分析 18 \/ 18 份/);
      await click('return-step');
      assert.equal(await page.locator('#confirmationNote').inputValue(), '环宇独立备注');
      const before = await page.locator('#stageWorkspace').innerHTML();
      await click('validation-dialog');
      assert.match(await page.locator('dialog').innerText(), /确定性校验/);
      await click('close-dialog');
      assert.equal(await page.locator('#stageWorkspace').innerHTML(), before);
    });
    await check('partial delivery has its own reason, counts and balanced voucher entries', async () => {
      await select('qingsong');
      await percent(40);
      assert.match(await text(), /已交付 12 张凭证，剩余 1 组待补证/);
      assert.doesNotMatch(await text(), /采购合同|付款差额/);
      await page.screenshot({ path: path.join(OUT, 'partial-delivery-1440.png') });
      await page.locator('[data-action="stage"][data-stage="3"]').click();
      assert.equal(await page.locator('#stageWorkspace tbody tr').count(), 12);
      await click('voucher-dialog');
      assert.match(await page.locator('dialog').innerText(), /青松智能.*2026-03/);
      await click('close-dialog');
      await page.locator('[data-action="stage"][data-stage="4"]').click();
      assert.match(await page.locator('#stageWorkspace').innerText(), /12 张凭证已交付/);
      await percent(40);
      await click('return-step');
      await page.locator('[data-action="tab"][data-tab="archive"]').click();
      assert.match(await text(), /部分交付，整期未归档/);
      await click('archive-voucher');
      assert.match(await page.locator('dialog').innerText(), /借贷平衡/);
      assert.match(await page.locator('dialog').innerText(), /已交付/);
      await page.screenshot({ path: path.join(OUT, 'archived-voucher-1440.png') });
      await click('close-dialog');
    });
    await check('archive entries open immediately in a modal and preserve table, focus and scroll', async () => {
      for (const width of [1440, 390]) {
        await page.setViewportSize({ width, height: width === 390 ? 844 : 900 });
        await select('juxianda');
        await page.locator('[data-action="tab"][data-tab="archive"]').click();
        const rowButton = page.locator('[data-action="archive-voucher"]').nth(1);
        await rowButton.scrollIntoViewIfNeeded();
        const before = await page.evaluate(() => ({ scrollY, html: document.querySelector('main').innerHTML, tableX: document.querySelector('main .table-scroll').scrollLeft }));
        await rowButton.click();
        assert.equal(await page.locator('dialog').isVisible(), true);
        assert.equal(await page.locator('dialog').evaluate(el => el.matches(':modal')), true);
        const detail = await page.locator('dialog').innerText();
        assert.match(detail, /凭证分录 · 记-002/);
        assert.match(detail, /聚贤达.*2026-02/);
        assert.match(detail, /已归档/);
        assert.match(detail, /借方金额[\s\S]*贷方金额[\s\S]*16,080\.00/);
        const box = await page.locator('dialog').boundingBox();
        assert.ok(box.x >= 0 && box.y >= 0 && box.x + box.width <= width && box.y + box.height <= (width === 390 ? 844 : 900));
        assert.equal(await page.locator('dialog').evaluate(el => el.scrollWidth <= el.clientWidth), true);
        assert.equal(await page.locator('dialog .table-scroll').evaluate(el => el.scrollWidth <= el.clientWidth), true);
        assert.equal((await page.locator('main').innerHTML()).replaceAll(' style=""', ''), before.html.replaceAll(' style=""', ''));
        await page.screenshot({ path: path.join(OUT, 'archive-entry-modal-' + width + '.png') });
        if (width === 1440) await page.keyboard.press('Escape');
        else await page.locator('dialog [data-action="close-dialog"]').click();
        await page.waitForFunction(() => document.activeElement?.dataset.action === 'archive-voucher');
        assert.equal(await rowButton.evaluate(el => el === document.activeElement), true);
        assert.equal(await page.evaluate(() => scrollY), before.scrollY);
        assert.equal(await page.locator('main .table-scroll').evaluate(el => el.scrollLeft), before.tableX);
        assert.equal((await page.locator('main').innerHTML()).replaceAll(' style=""', ''), before.html.replaceAll(' style=""', ''));
        await page.locator('#archivePeriod').selectOption('2026-01');
        await click('archive-voucher');
        assert.match(await page.locator('dialog').innerText(), /2026-01/);
        assert.doesNotMatch(await page.locator('dialog').innerText(), /2026-02/);
        await click('close-dialog');
      }
      await page.setViewportSize({ width: 1440, height: 900 });
    });
    await check('new enterprise starts empty; upload and analysis update the next task', async () => {
      await select('xinqiyuan');
      await percent(0);
      await page.screenshot({ path: path.join(OUT, 'new-enterprise-1440.png') });
      await page.locator('[data-action="tab"][data-tab="history"]').click();
      assert.match(await text(), /暂无往期数据/);
      await page.locator('[data-action="tab"][data-tab="archive"]').click();
      assert.match(await text(), /暂无已归档凭证/);
      await click('back-current');
      await click('upload-dialog'); await click('upload');
      await percent(20);
      assert.match(await text(), /正在分析本期资料/);
      for (const stage of [2, 3, 4]) assert.equal(await page.locator('[data-action="stage"][data-stage="' + stage + '"]').isDisabled(), true);
      await click('files-dialog');
      assert.match(await page.locator('dialog').innerText(), /本批已接收 4 份/);
      await click('close-dialog');
      await page.screenshot({ path: path.join(OUT, 'single-stage-analysis-1440.png') });
      await click('processing-details');
      assert.match(await page.locator('dialog').innerText(), /正在分析/);
      await click('close-dialog');
      if (!(await page.locator('[data-action="simulate-analysis"]').isVisible())) await page.locator('.sidebar-foot summary').click();
      await click('simulate-analysis');
      await percent(40);
      await click('confirm'); await click('validate'); await percent(60);
      await click('generate'); await click('review'); await percent(80);
      await click('archive-current'); await percent(100);
      await click('open-archive');
      assert.match(await text(), /1 张凭证/);
      await page.reload();
      await percent(100);
      assert.match(await page.locator('h1').innerText(), /新启源/);
    });
    await check('voucher auxiliary accounting gate and complete current-period listing', async () => {
      await select('chengyuan');
      await page.locator('[data-action="all-vouchers"]').scrollIntoViewIfNeeded();
      const workbenchScroll = await page.evaluate(() => window.scrollY);
      await click('all-vouchers');
      assert.equal(await page.locator('dialog[open]').count(), 0);
      assert.equal(await page.locator('main tbody tr').count(), 4);
      assert.equal(await page.locator('#stageWorkspace').count(), 0);
      assert.equal(await page.locator('#voucherListTitle').innerText(), '本期全部凭证');
      await page.screenshot({ path: path.join(OUT, 'voucher-list-page-1440.png') });
      const listContent = await page.locator('main').innerHTML();
      await click('voucher-dialog');
      assert.match(await page.locator('dialog').innerText(), /承远供应链.*2026-03/);
      assert.match(await page.locator('dialog').innerText(), /待复核/);
      await click('close-dialog');
      assert.equal(await page.locator('main').innerHTML(), listContent);
      assert.equal(await page.locator('main tbody tr').count(), 4);
      await click('back-current');
      assert.ok(Math.abs(await page.evaluate(() => window.scrollY) - workbenchScroll) < 2);
      await percent(60);
      await page.setViewportSize({ width: 390, height: 844 });
      await click('all-vouchers');
      assert.equal(await page.locator('main tbody tr').count(), 4);
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
      await page.screenshot({ path: path.join(OUT, 'voucher-list-page-390.png') });
      await click('voucher-dialog');
      await page.keyboard.press('Escape');
      assert.equal(await page.locator('dialog[open]').count(), 0);
      await select('huanyu');
      assert.equal(await page.locator('#voucherListTitle').count(), 0);
      await select('chengyuan');
      await page.setViewportSize({ width: 1440, height: 900 });
      for (let i = 0; i < 3; i++) await click('review');
      assert.equal(await page.locator('[data-action="review"]').isDisabled(), true);
      await page.locator('#auxConfirmed').check();
      assert.equal(await page.locator('[data-action="review"]').isEnabled(), true);
      await click('review'); await percent(80);
    });
    await check('archive search matches number, summary, account and source within scope', async () => {
      await select('chengyuan');
      await page.locator('[data-action="tab"][data-tab="archive"]').click();
      for (const [term,count] of [['记-002',1],['费用结转',3],['管理费用',3],['业务组 004',1],['不存在的凭证',0]]) {
        await page.locator('#archiveQuery').fill(term);
        await page.locator('#archiveQuery').press('Enter');
        assert.equal(await page.locator('#archiveResults tbody tr').count(), count);
      }
      assert.match(await page.locator('#archiveResults').innerText(), /未找到匹配/);
      await click('clear-archive-search');
      assert.equal(await page.locator('#archiveResults tbody tr').count(), 8);
      await page.locator('#archiveQuery').fill('管理费用');
      await page.locator('#archiveStartDate').fill('2026-02-09');
      await page.locator('#archiveEndDate').fill('2026-02-12');
      await page.locator('#archiveSearchForm button[type="submit"]').click();
      assert.equal(await page.locator('#archiveResults tbody tr').count(), 2);
      assert.match(await page.locator('#archiveResultsStatus').innerText(), /96,100\.00/);
      const validResults = await page.locator('#archiveResults').innerHTML();
      await page.locator('#archiveStartDate').fill('2026-02-13');
      await page.locator('#archiveSearchForm button[type="submit"]').click();
      assert.match(await page.locator('#archiveSearchError').innerText(), /开始日期不能晚于结束日期/);
      assert.equal(await page.locator('#archiveResults').innerHTML(), validResults);
      await page.locator('#archiveStartDate').fill('2026-02-09');
      await page.locator('#archiveEndDate').press('Enter');
      assert.equal(await page.locator('#archiveSearchError').isVisible(), false);
      assert.equal(await page.locator('#archiveResults tbody tr').count(), 2);
      await click('clear-archive-search');
      assert.equal(await page.locator('#archiveStartDate').inputValue(), '');
      assert.equal(await page.locator('#archiveEndDate').inputValue(), '');
      await page.locator('#archiveQuery').fill('记-002');
      await page.locator('#archiveSearchForm button[type="submit"]').click();
      await click('archive-voucher');
      assert.match(await page.locator('dialog').innerText(), /记-002/);
      await click('close-dialog');
      assert.equal(await page.locator('#archiveQuery').inputValue(), '记-002');
      await page.screenshot({ path: path.join(OUT, 'archive-search-1440.png') });
      await page.setViewportSize({width:390,height:844});
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
      await page.locator('#archiveStartDate').fill('2026-02-09');
      await page.locator('#archiveEndDate').fill('2026-02-09');
      await page.locator('#archiveSearchForm button[type="submit"]').click();
      assert.equal(await page.locator('#archiveResults tbody tr').count(), 1);
      await page.screenshot({ path: path.join(OUT, 'archive-search-390.png') });
      await select('huanyu');
      await page.locator('[data-action="tab"][data-tab="archive"]').click();
      assert.equal(await page.locator('#archiveQuery').inputValue(), '');
      assert.equal(await page.locator('#archiveStartDate').inputValue(), '');
      await select('chengyuan');
      await page.locator('[data-action="tab"][data-tab="archive"]').click();
      assert.equal(await page.locator('#archiveQuery').inputValue(), '记-002');
      assert.equal(await page.locator('#archiveStartDate').inputValue(), '2026-02-09');
      await select('juxianda');
      await page.locator('[data-action="tab"][data-tab="archive"]').click();
      await page.locator('#archiveQuery').fill('记-002');
      await page.locator('#archiveStartDate').fill('2026-02-09');
      await page.locator('#archiveSearchForm button[type="submit"]').click();
      await page.locator('#archivePeriod').selectOption('2026-01');
      assert.equal(await page.locator('#archiveQuery').inputValue(), '');
      assert.equal(await page.locator('#archiveStartDate').inputValue(), '');
      await page.locator('#archivePeriod').selectOption('2026-02');
      assert.equal(await page.locator('#archiveQuery').inputValue(), '记-002');
      assert.equal(await page.locator('#archiveResults tbody tr').count(), 1);
      await page.setViewportSize({width:1440,height:900});
    });
    await check('object query is bounded to the selected enterprise', async () => {
      await select('huanyu');
      await click('objects-dialog');
      await page.locator('#objectQuery').fill('哪些业务缺少资料');
      await click('query-submit');
      assert.match(await page.locator('#queryResult').innerText(), /环宇新材料/);
      assert.doesNotMatch(await page.locator('#queryResult').innerText(), /聚贤达|CONTRACT|8,838/);
      await click('close-dialog');
      assert.equal(await page.locator('#confirmationNote').inputValue(), '环宇独立备注');
    });
    await check('no overflow at 1024 and 871; mobile drawer, primary action and keyboard work', async () => {
      for (const width of [1024, 871, 390]) {
        await page.setViewportSize({ width, height: width === 390 ? 844 : 900 });
        await select('huanyu');
        await page.evaluate(() => window.scrollTo(0, 0));
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
        assert.equal(await page.locator('main .primary').count(), 1);
        const b = await page.locator('main .primary').boundingBox();
        assert.ok(b.y >= 0 && b.y + b.height <= (width === 390 ? 844 : 900), JSON.stringify(b));
        await page.screenshot({ path: path.join(OUT, 'viewport-' + width + '.png') });
      }
      await click('open-menu');
      assert.equal(await page.locator('#companySearch').evaluate(el => el === document.activeElement), true);
      await page.keyboard.press('Shift+Tab');
      assert.equal(await page.locator('.mobile-close').evaluate(el => el === document.activeElement), true);
      await page.keyboard.press('Escape');
      assert.equal(await page.locator('#mobileMenu').evaluate(el => el === document.activeElement), true);
      await click('toggle-stages');
      assert.equal(await page.locator('[data-action="stage"][data-stage="4"]').isDisabled(), true);
      await page.locator('[data-action="stage"][data-stage="0"]').click();
      assert.equal(await page.locator('#stageWorkspace').getAttribute('data-stage'), '0');
      assert.equal(await page.locator('.stages').isVisible(), false);
      await page.screenshot({ path: path.join(OUT, 'single-stage-files-390.png') });
      await click('return-step');
      assert.equal(await page.locator('#stageWorkspace').getAttribute('data-stage'), '2');
      await page.locator('#confirmationNote').fill('手机备注');
      await click('confirm');
      assert.equal(await page.locator('#confirmationNote').inputValue(), '');
      await page.screenshot({ path: path.join(OUT, 'mobile-confirmation-390.png') });
    });
    await check('blocked storage is usable and file mode has no external dependencies', async () => {
      const isolated = await browser.newContext({ viewport: { width: 390, height: 844 } });
      await isolated.addInitScript(() => {
        Storage.prototype.getItem = () => { throw new Error('denied'); };
        Storage.prototype.setItem = () => { throw new Error('denied'); };
      });
      const p = await isolated.newPage(), localErrors = [], localRequests = [];
      p.on('pageerror', e => localErrors.push(e.message));
      p.on('request', r => localRequests.push(r.url()));
      await p.goto(pathToFileURL(path.join(ROOT, 'static/operator-workbench-demo.html')).href);
      assert.equal(await p.locator('#overallPercent').textContent(), '40');
      await p.locator('[data-action="confirm"]').click();
      assert.match(await p.locator('#currentTaskTitle').textContent(), /付款/);
      await p.locator('[data-action="tab"][data-tab="archive"]').click();
      await p.locator('#archiveQuery').fill('管理费用');
      await p.locator('#archiveStartDate').fill('2026-02-09');
      await p.locator('#archiveEndDate').fill('2026-02-09');
      await p.locator('#archiveSearchForm button[type="submit"]').click();
      assert.equal(await p.locator('#archiveResults tbody tr').count(), 1);
      assert.equal(localErrors.length, 0);
      assert.equal(localRequests.filter(url => /^https?:/.test(url)).length, 0);
      await isolated.close();
    });
    await check('double-click cannot accidentally confirm the next item', async () => {
      const isolated = await browser.newContext({ viewport: { width: 1440, height: 900 } });
      const p = await isolated.newPage();
      await p.goto(URL);
      const box = await p.locator('[data-action="confirm"]').boundingBox();
      await p.mouse.dblclick(box.x + box.width / 2, box.y + box.height / 2);
      assert.match(await p.locator('#currentTaskTitle').textContent(), /付款/);
      assert.match(await p.locator('.task-progress').textContent(), /1.*2/);
      await isolated.close();
    });
    assert.deepEqual(errors, []);
    assert.equal(requests.filter(r => r.type !== 'document').length, 0, JSON.stringify(requests));
    report.push({ name: 'no browser errors or runtime network requests', passed: true });
  } catch (error) {
    await page.screenshot({ path: path.join(OUT, 'failure.png'), fullPage: true });
    report.push({ name: 'failure', passed: false, error: error.stack });
    throw error;
  } finally {
    fs.writeFileSync(path.join(OUT, 'report.json'), JSON.stringify({ report, errors, requests }, null, 2));
    await browser.close();
  }
}
run().catch(error => { console.error(error); process.exitCode = 1; });
