// Every write targets a disposable authenticated fixture; never the retained Staging data.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),net=require('node:net');
const {spawn}=require('node:child_process'),{chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'output/playwright/materials');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'finwise-materials-'));fs.mkdirSync(OUT,{recursive:true});
 const socket=net.createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));const port=socket.address().port;await new Promise(r=>socket.close(r));
 const server=spawn('python3',['tests/materials_fixture_server.py','--root',temp,'--port',String(port)],{cwd:ROOT,stdio:['ignore','pipe','pipe']});let logs='',browser;server.stderr.on('data',b=>logs+=b);
 const base=`http://127.0.0.1:${port}`,report=[],errors=[],commands=[];
 const check=async(name,fn)=>{await fn();report.push({name,status:'PASS'});console.log('PASS',name);};
 try{
  for(let i=0;i<100;i++){if(server.exitCode!==null)throw Error(logs);try{if((await fetch(base+'/api/v1/health')).ok)break;}catch{}await delay(100);}
  browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().endsWith('/commands'))commands.push(r.postDataJSON());});
  const settle=()=>page.waitForFunction(()=>!state.busy),click=async a=>{await page.locator(`[data-action="${a}"]`).first().click();await settle();};
  const filter=async id=>{if(['VERIFY','verified'].includes(id))await page.locator('[data-filter="results"]').first().click();if(id==='ISSUE')id='all';await page.locator(`[data-action="material-filter"][data-filter="${id}"]`).first().click();};
  const counts=()=>page.evaluate(()=>state.overview.material_review.counts);
  await page.goto(base+'/static/operator.html');await page.locator('#username').fill('plan-author');await page.locator('#password').fill('IssuePlanTest!2026');await page.locator('#loginForm button').click();await page.locator('#currentTask').waitFor();
  await page.locator('[data-scope]').filter({hasText:'方案核对甲'}).click();await settle();
  await check('historical handoff opens material overview, not a generic file list',async()=>{await click('history-next-work');await page.locator('#materialWorkbench').waitFor();assert.match(await page.locator('.mat-history').innerText(),/2 项处理意见已记录，其中 2 项暂无法补充/);const c=await counts();assert.equal(c.records,9);assert.equal(c.awaiting_verification,7);assert.equal(c.source_verified,0);assert.equal(c.accounting_usable,0);assert.equal(c.needs_review,1);assert.equal(c.period_exceptions,1);});
  await check('three navigation entries separate problems from optional human verification',async()=>{assert.equal(await page.locator('.mat-filters button').count(),3);assert.equal((await counts()).issue_tasks,2);assert.doesNotMatch(await page.locator('.mat-filters').innerText(),/待人工核实|待确认|识别问题/);assert.equal(await page.locator('[data-material-record]').count(),0);await filter('results');assert.match(await page.locator('.mat-result-summary').innerText(),/系统提取检查通过/);assert.equal(await page.locator('#materialWorkbench .primary').count(),0);});
  await check('raw source and extracted values are visible and only visible records selectable',async()=>{await filter('VERIFY');assert(await page.locator('#materialTaskTitle').evaluate(e=>e===document.activeElement));assert.equal(await page.locator('[data-material-record]').count(),5);assert.equal(await page.locator('#materialWorkbench .primary').count(),1);await click('material-verify');assert.match(await page.locator('#notice').innerText(),/请选择|请先比较/);await page.locator('#materialNote').fill('已与原件逐字段核对');await page.locator('[data-material-record]').first().check();await page.locator('.mat-record [data-object]').first().click();await page.locator('#dialog[open]').waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('#materialNote').inputValue(),'已与原件逐字段核对');});
  await check('field comparisons are aligned and derived totals are not labeled direct matches',async()=>{const table=page.locator('.mat-comparison').first();assert.match(await table.innerText(),/字段.*原件数据.*提取结果.*系统检查/s);assert.match(await table.innerText(),/由原始字段计算/);assert.match(await table.innerText(),/格式规范化后一致/);assert.match(await page.locator('.goal').innerText(),/不是确认业务真实/);assert.equal(await page.locator('.mat-other [data-material-record]').count(),0);});
  await check('one confirmation persists identity and note, advances inline without financial release',async()=>{await click('material-verify');assert.equal((await counts()).source_verified,1);assert.equal((await counts()).accounting_usable,0);assert.equal(await page.evaluate(()=>state.overview.baseline.status),'DRAFT');assert.equal(commands.at(-1).payload.records.length,1);assert.ok(commands.at(-1).payload.task_id);assert.equal(await page.locator('#materialNote').inputValue(),'');});
  await check('defer asks only reason, preserves outstanding count and advances',async()=>{await filter('ISSUE');const before=await counts();await click('material-defer');assert.equal(await page.locator('#materialDeferForm textarea').count(),1);await page.locator('#materialReason').fill('已联系客户，暂无完整字段原件');await click('material-save-defer');const after=await counts();assert.equal(after.deferred,1);assert.equal(after.needs_review,before.needs_review);assert.equal(after.source_verified,1);await filter('deferred');assert.match(await page.locator('.record-note').innerText(),/plan-author/);assert.match(await page.locator('.record-note').innerText(),/仍待补充/);});
  await check('refresh restores enterprise and overview; source review can be revoked',async()=>{await page.reload();await page.locator('#materialWorkbench').waitFor();await filter('verified');assert.match(await page.locator('.mat-record').innerText(),/已与原件逐字段核对/);await click('material-revoke');assert.equal((await counts()).source_verified,0);});
  await check('all files remains secondary and return preserves scope',async()=>{await click('material-files');await page.locator('#receivedFiles').waitFor();await click('return-files');await page.locator('#materialWorkbench').waitFor();assert.equal(await page.evaluate(()=>scope().legal_entity_id),'方案核对甲');});
  await check('enterprise switch does not leak notes or review records',async()=>{await filter('VERIFY');await page.locator('#materialNote').fill('甲企业未提交备注');await page.locator('[data-scope]').filter({hasText:'方案核对乙'}).click();await settle();assert.equal(await page.locator('#materialWorkbench').count(),0);await page.locator('[data-scope]').filter({hasText:'方案核对甲'}).click();await settle();await page.locator('#materialWorkbench').waitFor();await filter('VERIFY');assert.equal(await page.locator('#materialNote').inputValue(),'');});
  await check('skip does not count completion and resume restores skipped work',async()=>{const before=await counts();await click('material-skip');assert.deepEqual(await counts(),before);await filter('all');});
  await check('explicit result entry reopens its skipped task instead of silently choosing another',async()=>{await filter('VERIFY');const task=await page.evaluate(()=>currentMaterialTask().id);await click('material-skip');await filter('results');await page.locator(`[data-task="${task}"]`).click();assert.equal(await page.evaluate(()=>currentMaterialTask().id),task);});
  await check('successful write with failed refresh retries the same command key',async()=>{await page.reload();await page.locator('#materialWorkbench').waitFor();await filter('VERIFY');await page.locator('[data-material-record]').first().check();let failed=false;await page.route('**/api/v1/workbench',async route=>{if(!failed){failed=true;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'隔离刷新失败'}})});}else await route.continue();});await click('material-verify');const key=commands.at(-1).idempotency_key;assert.match(await page.locator('#notice').innerText(),/隔离刷新失败/);await click('material-verify');assert.equal(commands.at(-1).idempotency_key,key);assert.equal((await counts()).source_verified,1);await page.unroute('**/api/v1/workbench');});
  await check('logout clears all unsaved selections and notes even for the same account',async()=>{await page.locator('#materialNote').fill('未提交备注不得跨登录会话');await page.locator('[data-material-record]').first().check();await page.locator('#logout').click();await page.locator('#username').waitFor();await page.locator('#username').fill('plan-author');await page.locator('#password').fill('IssuePlanTest!2026');await page.locator('#loginForm button').click();await page.locator('#materialWorkbench').waitFor();await filter('VERIFY');assert.equal(await page.locator('#materialNote').inputValue(),'');assert.equal(await page.locator('[data-material-record]:checked').count(),0);});
  await check('revoking the last record on page two reveals the remaining first page',async()=>{while((await counts()).source_verified<6){await filter('VERIFY');await page.locator('[data-material-record]').first().check();await click('material-verify');}await filter('verified');await page.locator('[data-action="material-page"][data-page="1"]').click();await click('material-revoke');assert.equal((await counts()).source_verified,5);assert.equal(await page.locator('.mat-record').count(),5);assert.doesNotMatch(await page.locator('#materialWorkbench').innerText(),/尚无人工核实记录/);});
  for(const width of [1440,1040,390])await check(`layout ${width}px and current action accessible`,async()=>{await page.setViewportSize({width,height:width===390?844:900});await filter('VERIFY');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>{clearNotice();window.scrollTo(0,0);});await page.screenshot({path:path.join(OUT,`material-first-${width}.png`)});await page.locator('[data-action="material-verify"]').scrollIntoViewIfNeeded();assert(await page.locator('[data-action="material-verify"]').isVisible());await page.screenshot({path:path.join(OUT,`material-${width}.png`),fullPage:true});});
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify({report,errors,temp},null,2));console.log(JSON.stringify({passed:report.length,temp}));
 }catch(e){console.error(logs.slice(-2000));throw e;}finally{await browser?.close();server.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exitCode=1;});
