const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),net=require('node:net');
const {spawn}=require('node:child_process'),{chromium}=require('playwright');
const {guided}=require('./operator_guided_helpers_browser.cjs');
(async()=>{
 const root=path.resolve(__dirname,'..'),out=path.join(root,'output/playwright/bank-accounts');fs.mkdirSync(out,{recursive:true});
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'finwise-bank-ui-')),socket=net.createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));const port=socket.address().port;await new Promise(r=>socket.close(r));
 const server=spawn('python3',['tests/bank_accounts_fixture_server.py','--root',temp,'--port',String(port)],{cwd:root,stdio:['ignore','pipe','pipe']});let logs='',browser;server.stderr.on('data',b=>logs+=b);const base=`http://127.0.0.1:${port}`,errors=[],flows=[];
 try{
  for(let i=0;i<120;i++){if(server.exitCode!==null)throw Error(logs);try{if((await fetch(base+'/api/v1/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.message));const g=guided(page);
  await page.goto(base+'/static/operator.html');await page.locator('#username').fill('plan-author');await page.locator('#password').fill('IssuePlanTest!2026');await page.locator('#loginForm button').click();await page.locator('#currentTask').waitFor();
  await page.locator('[data-scope]').filter({hasText:'方案核对甲'}).click();await page.waitForFunction(()=>!state.busy);
  await page.locator('[data-action="accounts-open"]').first().click();await page.locator('#bankTitle').waitFor();assert.match(await page.locator('#workspace').innerText(),/0 个已登记账户/);
  await page.locator('[data-action="accounts-statement"]').click();await page.locator('#bankAccountForm').waitFor();assert.match(await page.locator('#workspace').innerText(),/已识别银行：中国农业银行/);
  assert.equal(await page.locator('input[name="account_number"]:visible').count(),0);assert.equal(await page.locator('input[name="account_number"]').getAttribute('required'),null);
  assert.notEqual(await page.locator('.decision-source').getAttribute('open'),null);await page.getByText('查看原件已提供的信息（无需重复填写）',{exact:true}).click();assert.match(await page.locator('.mat-task').innerText(),/001-234567890/);await page.getByText('查看原件已提供的信息（无需重复填写）',{exact:true}).click();
  flows.push('按文件名识别银行，账号选填，原件已有账号按需查看');
  for(const [width,height] of [[1440,900],[1040,900],[390,844]]){await page.setViewportSize({width,height});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('#bankAccountForm .primary:visible').count(),1);await page.screenshot({path:path.join(out,`candidate-${width}.png`),fullPage:true});}
  flows.push('1440/1040/390 无页面溢出、唯一主操作');await page.setViewportSize({width:1040,height:900});
  await page.getByRole('button',{name:'查看完整原件',exact:true}).click();await page.locator('#dialog[open]').waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('input[name="bank_name"]').inputValue(),'中国农业银行');flows.push('查看原件并返回，账户草稿保留');
  await g.choose('defer_material_issue');await page.locator('#materialReason').fill('等待企业确认账户归属');await g.finish();await page.waitForFunction(()=>!state.busy&&state.overview.material_review.counts.deferred===1);
  await page.locator('[data-action="accounts-open"]').first().click();await page.locator('[data-action="accounts-statement"]').click();await page.locator('#bankAccountForm').waitFor();assert.match(await page.locator('.mat-task').innerText(),/农业银行测试流水/);flows.push('暂无法确认仅记录原因，可从原流水入口恢复');
  await g.choose('confirm_statement_account');await g.next();await page.locator('input[name="confirmed"]').check();await g.back();await page.locator('input[name="bank_name"]').fill('中国农业银行');assert.equal(await page.locator('input[name="confirmed"]').isChecked(),false);flows.push('账户信息变化后必须重新勾选确认');await g.next();
  await page.locator('input[name="confirmed"]').check();let commands=0;const countCommand=r=>{if(r.url().includes('/api/v1/commands'))commands++;};page.on('request',countCommand);await g.source();await page.getByRole('button',{name:'查看完整原件',exact:true}).click();await page.locator('#dialog[open]').waitFor();await page.keyboard.press('Escape');assert.equal(commands,0);assert.equal(await page.locator('input[name="confirmed"]').isChecked(),true);flows.push('表单已确认时查看原件不触发写入');await page.locator('input[name="confirmed"]').press('Enter');await g.settle();assert.equal(commands,0);assert.equal(await page.locator('.decision-summary:visible').count(),0);await g.next();assert(await page.locator('.decision-summary').isVisible());assert.equal(commands,0);page.off('request',countCommand);await g.commit();await page.waitForFunction(()=>!state.busy&&state.overview.bank_accounts.accounts.length===1);flows.push('确认勾选上的Enter不推进，核对摘要后明确提交才保存银行');
  let result=await page.evaluate(()=>({accounts:state.overview.bank_accounts.accounts.length,status:state.overview.bank_accounts.statements[0].status,period:state.overview.material_review.counts.period_exceptions,verified:state.overview.material_review.counts.source_verified,baseline:state.overview.baseline.status}));
  assert.equal(result.status,'LINKED');assert.equal(result.period,1);assert.equal(result.verified,0);assert.equal(result.baseline,'DRAFT');flows.push('一次确认整份关联 → 下一项，跨期及账务门禁保留');
  assert.equal(await page.evaluate(()=>materialUI.screen),'summary');assert.match(await page.locator('.mat-group-totals').innerText(),/银行归属已确认/);
  await page.locator('[data-action="material-return-list"]').click();await page.locator('[data-action="material-filter"][data-filter="all"]').first().click();flows.push('暂缓恢复完成后展示本组结果，由用户返回可处理问题列表');
  await page.getByRole('button',{name:'已有成果',exact:true}).click();await page.getByRole('button',{name:'查看提取值并核实'}).click();await page.locator('[data-material-record]:visible').check();await g.finish();await page.waitForFunction(()=>!state.busy&&state.overview.material_review.counts.source_verified===1);flows.push('关联后可逐条人工核实，原件重新校验通过');
  await page.reload();await page.locator('[data-action="accounts-open"]').first().waitFor();await page.locator('[data-action="accounts-open"]').first().click();assert.match(await page.locator('#workspace').innerText(),/未填写 · 按银行记账/);flows.push('不填账号确认银行，刷新后分配恢复');
  await page.locator('[data-action="accounts-new"]').click();await page.getByText('补充账号等信息（选填）',{exact:true}).click();await page.locator('input[name="holder"]').fill('未提交的甲企业草稿');
  await page.locator('[data-scope]').filter({hasText:'方案核对乙'}).click();await page.waitForFunction(()=>!state.busy);await page.locator('[data-action="accounts-open"]').first().click();assert.doesNotMatch(await page.locator('#workspace').innerText(),/001-234567890|未提交的甲企业草稿/);
  await page.locator('[data-action="accounts-new"]').click();await page.getByText('补充账号等信息（选填）',{exact:true}).click();await page.locator('input[name="account_number"]').fill('00234567890');await page.locator('input[name="holder"]').fill('合成乙企业');await page.locator('input[name="bank_name"]').fill('中国银行');await page.locator('input[name="confirmed"]').check();await page.locator('#bankAccountForm button[type="submit"]').click();await page.waitForFunction(()=>!state.busy&&state.overview.bank_accounts.accounts.length===1);flows.push('企业隔离、未提交内容不串企业、可选录入明确账号');
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({status:'PASS',flows,result,errors},null,2));console.log(JSON.stringify({status:'PASS',flows,result}));
 }finally{if(browser)await browser.close();server.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exitCode=1;});
