const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../static/operator.js'),'utf8');
function app(){
 const c=vm.createContext({state:{overview:{baseline_validation:{status:'VALID'},artifacts:[{object_id:'file',status:'ACTIVE',data:{observed_period:'2026-01',parse_status:'FAILED'}}],material_review:{counts:{issue_tasks:2,human_issue_tasks:1,system_issue_tasks:1,needs_review:8},tasks:[{id:'s',kind:'PARSE',artifact_id:'file',triage:{version:'issue-triage-v1',route:'SYSTEM'}},{id:'h',kind:'BILL'}]},blockers:[],pending_confirmation_cards:[],vouchers:[],data_readiness:{counts:{needs_review:8,period_exceptions:2},usable_results:[]}}},scope:()=>({accounting_period_id:'2026-01'}),historicalActionable:()=>false,historyCanWaitForCurrent:()=>false});
 vm.runInContext("const readiness=()=>state.overview.data_readiness;function materialSystemTask(t){return t.triage?.route==='SYSTEM';}function operatorMaterialIsSystemTask(t){return materialSystemTask(t);}function operatorRecordedMaterialOpinion(t){return (t.material_opinions||[]).find(o=>o&&o.valid===true&&(o.status==='SAVED_NOT_EXECUTED'||typeof o.text==='string'))||null;}"+source.slice(source.indexOf('function materialCounts()'),source.indexOf('const fileById'))+source.slice(source.indexOf('function currentTask()'),source.indexOf('function taskShell')),c);return c;
}
test('home prioritizes human issue tasks while raw record counts remain unchanged',()=>{const c=app();assert.equal(c.currentTask(),'issues');assert.equal(c.materialCounts().needs_review,8);assert.equal(c.materialCounts().human_issue_tasks,1);assert.equal(c.materialCounts().system_issue_tasks,1);assert.equal(c.materialCounts().issue_tasks,2);});
test('system-only failed parsing no longer demands parsing/upload from the home primary task',()=>{const c=app();c.state.overview.material_review.counts.human_issue_tasks=0;assert.equal(c.currentTask(),'system-issues');});
test('old tasks without triage remain human when added counts are absent',()=>{const c=app();delete c.state.overview.material_review.counts.human_issue_tasks;delete c.state.overview.material_review.counts.system_issue_tasks;assert.equal(c.materialCounts().human_issue_tasks,1);assert.equal(c.materialCounts().system_issue_tasks,1);assert.equal(c.currentTask(),'issues');});
test('recorded processing opinions leave human work and become a separate waiting state',()=>{const c=app();const human=c.state.overview.material_review.tasks.find(t=>t.id==='h');human.material_opinions=[{valid:true,status:'SAVED_NOT_EXECUTED',text:'按原交易日期归属二月'}];assert.equal(c.materialCounts().human_issue_tasks,0);assert.equal(c.materialCounts().selected_processing_tasks,1);assert.equal(c.currentTask(),'selected-issues');});
