import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const viewSource = readFileSync(resolve(__dirname, 'VoucherWorkbenchView.vue'), 'utf8')
const clientSource = readFileSync(resolve(__dirname, '../api/client.js'), 'utf8')
const routerSource = readFileSync(resolve(__dirname, '../router/index.js'), 'utf8')

describe('VoucherWorkbenchView', () => {
  it('wires the voucher workbench page, API client, and route', () => {
    expect(viewSource).toContain('凭证生成工作台')
    expect(viewSource).toContain('生成草稿并 AI 推荐')
    expect(viewSource).toContain('当前操作主体')
    expect(viewSource).toContain('选择企业主体')
    expect(viewSource).toContain('选择工作期间')
    expect(viewSource).toContain('selectedEnterpriseId')
    expect(viewSource).toContain('selectedPeriodPackageId')
    expect(viewSource).toContain('enterpriseOptions')
    expect(viewSource).toContain('periodOptions')
    expect(viewSource).not.toContain('选择月度工作包')
    expect(viewSource).not.toContain('`${item.company} · ${item.period}`')
    expect(viewSource).toContain('工作包待确认')
    expect(viewSource).toContain('凭证待确认')
    expect(viewSource).toContain('activePackage?.company')
    expect(viewSource).toContain('activePackage?.period')
    expect(viewSource).toContain('workspace.selectPackage(packageId)')
    expect(viewSource).toContain('凭证处理流程')
    expect(viewSource).toContain('生成草稿')
    expect(viewSource).toContain('AI 推荐科目')
    expect(viewSource).toContain('人工确认')
    expect(viewSource).toContain('待处理凭证列表')
    expect(viewSource).toContain('先选择一张凭证，再在右侧核对并确认')
    expect(viewSource).toContain('当月整理摘要')
    expect(viewSource).toContain('完全配对')
    expect(viewSource).toContain('差额补齐')
    expect(viewSource).toContain('单边补齐')
    expect(viewSource).toContain('历史延续')
    expect(viewSource).toContain('api.sourceLedgers.summary')
    expect(viewSource).toContain('taskTypeLabel')
    expect(viewSource).toContain('voucherTaskType')
    expect(viewSource).toContain('请按顺序核对 AI 推荐、异常提示和分录金额')
    expect(viewSource).toContain('第 1 步：原始数据')
    expect(viewSource).toContain('银行流水')
    expect(viewSource).toContain('发票信息')
    expect(viewSource).toContain('匹配记录')
    expect(viewSource).toContain('sourceBankTransaction')
    expect(viewSource).toContain('sourceBankTransactions')
    expect(viewSource).toContain('sourceInvoice')
    expect(viewSource).toContain('sourceInvoices')
    expect(viewSource).toContain('sourceMatches')
    expect(viewSource).toContain('sourceGroupTypeLabel')
    expect(viewSource).toContain('组合来源')
    expect(viewSource).toContain('missingSourceTreatment')
    expect(viewSource).toContain('缺失发票，建议会计处理')
    expect(viewSource).toContain('缺失流水，建议会计处理')
    expect(viewSource).toContain('调整处理方式')
    expect(viewSource).toContain('treatmentForm')
    expect(viewSource).toContain('applyTreatmentAdjustment')
    expect(viewSource).toContain('ONE_INVOICE_MULTIPLE_BANK_TRANSACTIONS')
    expect(viewSource).toContain('ONE_BANK_TRANSACTION_MULTIPLE_INVOICES')
    expect(viewSource).toContain('v-for="(transaction, index) in sourceBankTransactions"')
    expect(viewSource).toContain('v-for="(invoice, index) in sourceInvoices"')
    expect(viewSource).toContain('sourceInvoiceSellerName')
    expect(viewSource).toContain('invoiceSellerName')
    expect(viewSource).toContain('invoiceBuyerName')
    expect(viewSource).toContain('invoiceRawValue')
    expect(viewSource).toContain("'销方名称'")
    expect(viewSource).toContain('matched-value')
    expect(viewSource).toContain('matching-field')
    expect(viewSource).toContain('sourceMatch')
    expect(viewSource).toContain('function normalizeSourceData(value)')
    expect(viewSource).toContain('JSON.parse(value)')
    expect(viewSource).toContain('voucher.source_data ?? voucher.sourceData')
    expect(viewSource).toContain('function invoiceDirectionLabel(value)')
    expect(viewSource).toContain("OUTPUT: '销项发票'")
    expect(viewSource).toContain('function matchMethodLabel(value)')
    expect(viewSource).toContain('grid-template-columns: minmax(520px, 0.78fr) minmax(520px, 0.52fr)')
    expect(viewSource).toContain('size="large"')
    expect(viewSource).toContain('position: sticky')
    expect(viewSource).toContain('第 2 步：AI 推荐说明')
    expect(viewSource).toContain('第 3 步：人工确认')
    expect(viewSource).toContain('AI 置信度')
    expect(viewSource).toContain('借方')
    expect(viewSource).toContain('贷方')
    expect(viewSource).toContain('刷新')
    expect(viewSource).toContain('@click="refreshVouchers"')
    expect(viewSource).toContain('async function refreshVouchers()')
    expect(viewSource).toContain('const didRefresh = await loadVouchers(activePackageId.value)')
    expect(viewSource).toContain('凭证列表已刷新')
    expect(viewSource).not.toContain('@click="loadVouchers"')
    expect(viewSource).toContain('全部')
    expect(viewSource).toContain('待确认')
    expect(viewSource).toContain('已确认')
    expect(viewSource).toContain('异常')
    expect(viewSource).toContain("value: 'fullMatch'")
    expect(viewSource).toContain("value: 'difference'")
    expect(viewSource).toContain("value: 'singleSource'")
    expect(viewSource).toContain("value: 'historical'")
    expect(viewSource).toContain('确认凭证')
    expect(viewSource).toContain('标记不正确')
    expect(viewSource).toContain('重新匹配')
    expect(viewSource).toContain('撤销确认')
    expect(viewSource).toContain('恢复待确认')
    expect(viewSource).toContain('rematchDialogVisible')
    expect(viewSource).toContain("width=\"min(1280px, 92vw)\"")
    expect(viewSource).toContain('rematchInvoiceSearch')
    expect(viewSource).toContain('rematchBankSearch')
    expect(viewSource).toContain('rematchMode')
    expect(viewSource).toContain('rematchModeOptions')
    expect(viewSource).toContain('保留流水重选发票')
    expect(viewSource).toContain('保留发票重选流水')
    expect(viewSource).toContain('两边都重选')
    expect(viewSource).toContain('filteredRematchInvoiceCandidates')
    expect(viewSource).toContain('filteredRematchBankCandidates')
    expect(viewSource).toContain('placeholder="搜索日期、对方、金额、发票号或理由"')
    expect(viewSource).toContain('rematchCandidatePopover')
    expect(viewSource).toContain('rematchCandidateDirectionLabel')
    expect(viewSource).toContain('rematchCandidateCounterpartyLabel')
    expect(viewSource).toContain('rematchPairPreview')
    expect(viewSource).toContain('新配对预览')
    expect(viewSource).toContain(':class="rematchPanelClass"')
    expect(viewSource).toContain('const rematchPanelClass = computed')
    expect(viewSource).toContain('rematch-panels-single')
    expect(viewSource).toContain('rematch-panels-dual')
    expect(viewSource).toContain('rematch-table-wrap')
    expect(viewSource).toContain('overflow-x: auto')
    expect(viewSource).toContain('发票方向')
    expect(viewSource).toContain('收付方向')
    expect(viewSource).toContain('候选状态')
    expect(viewSource).toContain('rematchCandidateStatusLabel')
    expect(viewSource).toContain('rematchCandidateRowClass')
    expect(viewSource).toContain('isRematchCandidateSelectable')
    expect(viewSource).toContain('selectedRematchInvoiceIds')
    expect(viewSource).toContain('selectedRematchBankIds')
    expect(viewSource).toContain('toggleRematchInvoice')
    expect(viewSource).toContain('toggleRematchBank')
    expect(viewSource).toContain('payload.invoice_ids')
    expect(viewSource).toContain('payload.bank_transaction_ids')
    expect(viewSource).toContain('openRematchDialog')
    expect(viewSource).toContain('applyRematch')
    expect(viewSource).toContain('应用重新匹配')
    expect(viewSource).toContain('async function reopenVoucher()')
    expect(viewSource).toContain('canReopenVoucher')
    expect(viewSource).toContain('async function rejectVoucher()')
    expect(viewSource).toContain('api.vouchers.reject')
    expect(viewSource).toContain('api.vouchers.reopen')
    expect(viewSource).toContain('api.vouchers.rematchCandidates')
    expect(viewSource).toContain('api.vouchers.rematch')
    expect(viewSource).toContain('凭证已标记为不正确')
    expect(viewSource).toContain('凭证已恢复为待确认')
    expect(viewSource).toContain('凭证已重新匹配')
    expect(viewSource).toContain("REJECTED: '已驳回'")
    expect(viewSource).toContain('function packageStatusLabel(value)')
    expect(viewSource).toContain("PENDING_CONFIRMATION: '待确认'")
    expect(viewSource).toContain('function validationErrorLabel(value)')
    expect(viewSource).toContain("DATE_OUT_OF_PERIOD: '凭证日期不在当前会计期间'")
    expect(viewSource).toContain("SOURCE_REASSIGNED: '来源已被其他凭证重新匹配'")
    expect(viewSource).toContain('validationErrorLabels.join')
    expect(viewSource).toContain('function selectNextPendingVoucher(previousVoucherId)')
    expect(viewSource).toContain('selectNextPendingVoucher(voucherId)')
    expect(viewSource).toContain('await workspace.loadWorkspace(packageId)')
    expect(viewSource).toContain('api.vouchers.generate')
    expect(viewSource).toContain('created_vouchers')
    expect(viewSource).toContain('本次没有生成新的凭证草稿')
    expect(viewSource).toContain('api.vouchers.confirm')
    expect(viewSource).toContain("confirmed_by: 'operator'")
    expect(viewSource).toContain('function isConfirmed(voucher)')
    expect(viewSource).toContain('if (isRejected(voucher)) return false')
    expect(viewSource).toContain('function formatConfidence(value)')
    expect(viewSource).toContain('return `${Math.round(confidence)}%`')
    expect(viewSource).not.toContain('confidence * 100')
    expect(viewSource).toContain('voucherLoadRequestId')
    expect(viewSource).toContain('requestId !== voucherLoadRequestId')
    expect(viewSource).toContain('packageId !== activePackageId.value')
    expect(clientSource).toContain('vouchers')
    expect(clientSource).toContain('/monthly-packages/${packageId}/vouchers')
    expect(clientSource).toContain('/monthly-packages/${packageId}/vouchers/generate')
    expect(clientSource).toContain('/vouchers/${voucherId}/confirm')
    expect(clientSource).toContain('/vouchers/${voucherId}/reject')
    expect(clientSource).toContain('/vouchers/${voucherId}/reopen')
    expect(clientSource).toContain('/vouchers/${voucherId}/rematch-candidates')
    expect(clientSource).toContain('/vouchers/${voucherId}/rematch')
    expect(clientSource).toContain('/vouchers/${voucherId}/treatment-adjustment')
    expect(routerSource).toContain('/vouchers')
    expect(routerSource).toContain('../views/VoucherWorkbenchView.vue')
  })
})
