SMALL_BUSINESS_SUBJECTS = [
    {
        "code": "1001",
        "name": "库存现金",
        "category": "ASSET",
        "normal_balance": "DEBIT",
        "parent_code": None,
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "1002",
        "name": "银行存款",
        "category": "ASSET",
        "normal_balance": "DEBIT",
        "parent_code": None,
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "1122",
        "name": "应收账款",
        "category": "ASSET",
        "normal_balance": "DEBIT",
        "parent_code": None,
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "1123",
        "name": "预付账款",
        "category": "ASSET",
        "normal_balance": "DEBIT",
        "parent_code": None,
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "1221",
        "name": "其他应收款",
        "category": "ASSET",
        "normal_balance": "DEBIT",
        "parent_code": None,
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "2202",
        "name": "应付账款",
        "category": "LIABILITY",
        "normal_balance": "CREDIT",
        "parent_code": None,
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "2203",
        "name": "预收账款",
        "category": "LIABILITY",
        "normal_balance": "CREDIT",
        "parent_code": None,
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "2241",
        "name": "其他应付款",
        "category": "LIABILITY",
        "normal_balance": "CREDIT",
        "parent_code": None,
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "2221",
        "name": "应交税费",
        "category": "LIABILITY",
        "normal_balance": "CREDIT",
        "parent_code": None,
        "is_leaf": False,
        "allow_voucher": False,
        "is_common": True,
    },
    {
        "code": "222101",
        "name": "应交增值税",
        "category": "LIABILITY",
        "normal_balance": "CREDIT",
        "parent_code": "2221",
        "is_leaf": False,
        "allow_voucher": False,
        "is_common": True,
    },
    {
        "code": "22210101",
        "name": "进项税额",
        "category": "LIABILITY",
        "normal_balance": "DEBIT",
        "parent_code": "222101",
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "22210102",
        "name": "销项税额",
        "category": "LIABILITY",
        "normal_balance": "CREDIT",
        "parent_code": "222101",
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "5001",
        "name": "主营业务收入",
        "category": "REVENUE",
        "normal_balance": "CREDIT",
        "parent_code": None,
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "5401",
        "name": "主营业务成本",
        "category": "COST",
        "normal_balance": "DEBIT",
        "parent_code": None,
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "5602",
        "name": "管理费用",
        "category": "EXPENSE",
        "normal_balance": "DEBIT",
        "parent_code": None,
        "is_leaf": False,
        "allow_voucher": False,
        "is_common": True,
    },
    {
        "code": "560201",
        "name": "办公费",
        "category": "EXPENSE",
        "normal_balance": "DEBIT",
        "parent_code": "5602",
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "560202",
        "name": "差旅费",
        "category": "EXPENSE",
        "normal_balance": "DEBIT",
        "parent_code": "5602",
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "560203",
        "name": "服务费",
        "category": "EXPENSE",
        "normal_balance": "DEBIT",
        "parent_code": "5602",
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
    {
        "code": "5603",
        "name": "财务费用",
        "category": "EXPENSE",
        "normal_balance": "DEBIT",
        "parent_code": None,
        "is_leaf": False,
        "allow_voucher": False,
        "is_common": True,
    },
    {
        "code": "560301",
        "name": "手续费",
        "category": "EXPENSE",
        "normal_balance": "DEBIT",
        "parent_code": "5603",
        "is_leaf": True,
        "allow_voucher": True,
        "is_common": True,
    },
]
